Vagrant.configure("2") do |config|
  config.vm.box = "digital_ocean"
  config.ssh.private_key_path = "C:\\Users\\Egor_Kazitski/.ssh/id_rsa"
  config.vm.provider :digital_ocean do |provider|
    provider.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.nfs.functional = false
    provider.vm.allowed_synced_folder_types = :rsync
    provider.token = "{{PROVIDER_TOKEN}}"
    provider.image = "ubuntu-18-04-x64"
    provider.region = "nyc1"
    provider.size = 's-1vcpu-1gb'
    provider.backups_enabled = false
    provider.private_networking = false
    provider.ipv6 = false
    provider.monitoring = false
  end
end
